### ISSUE TITLE
安装完依赖后项目跑不起来

### ISSUE THREAD

**Issue by AprildreamMI** [mengdebiao/vue-electron-notes#1]
控制台报错
`Uncaught TypeError: localforage.config is not a function`
**并无其他操作**

**Comment by mengdebiao** [comment]
> 控制台报错
> `Uncaught TypeError: localforage.config is not a function`
> **并无其他操作**

@AprildreamMI 我多次重试了一下，并无此报错，能不能提供一下详细的截图报错看看

**Comment by AprildreamMI** [comment]
> > 控制台报错
> > `Uncaught TypeError: localforage.config is not a function`
> > **并无其他操作**
> 
> @AprildreamMI 我多次重试了一下，并无此报错，能不能提供一下详细的截图报错看看
![UHMo1x.png](https://s1.ax1x.com/2020/07/22/UHMo1x.png)
+ 并未更改有关包版本

**Comment by mengdebiao** [comment]
@AprildreamMI nedb 有个依赖包 localforage，localforage 一天前左右升级了 1.8.0 版本修改了 api，我已将 localforage 版本固定在 1.7.x 版本内， 你可以重新拉代码后安装依赖再试下

**Comment by AprildreamMI** [comment]
> @AprildreamMI nedb 有个依赖包 localforage，localforage 一天前左右升级了 1.8.0 版本修改了 api，我已将 localforage 版本固定在 1.7.x 版本内， 你可以重新拉代码后安装依赖再试下
OK
