### ISSUE TITLE
请教问题的issue

### ISSUE THREAD

**Issue by yayxs** [mengdebiao/vue-electron-notes#2]
我想请问一下大佬，目前初始化项目架子
 - 是不是基于新的脚手架 vue-cli-plugin-electron-builder  **这个方案会好些**
 - 还有一个是  star 数 挺高  electron-vue **不过cli 的版本以及 electron的版本目前还很低**

---
问题二是：
理论上，单独的一个单纯的 `Vue` 项目和一个 单纯的 `electron ` 项目  这个方案也是可行的吧？在想它俩之间怎么通信呢？应该是 electron 是外边的壳子 然后套一个  Vue ？

**Comment by mengdebiao** [comment]
@yayxs 
1、electron-vue 推出的时间比较早，内部实现确实写得挺好的，当然拥有比较多的用户数 star 数，但是已经处于两年多无人维护的状态了。vue-cli-plugin-electron-builder 虽然现在的 star 数比较少，但维护及时，直接就是基于 vue-cli 开发，更加适合 vue 的使用约定，最近的新版本也已经直接支持 electron9.0 了，我个人还是极力推荐 vue-cli-plugin-electron-builder 的。
2、某种情况下，你这么理解也没毛病，electron 是外边的壳子(主进程)，里面塞一个 vue 项目(渲染进程)，正常情况下你要分开两个项目没问题，但是如果你要涉及到不同进程之间的通讯，那你就只能把渲染进程放进到主进程里面了，electron就是这么规定的，除此之外比无他法，如果您有更好的思路，欢迎给我留言，一起学习😁

**Comment by yayxs** [comment]
嗯，首先很感谢@mengdebiao的回复，关于 `electron-vue` 这个方案和 `vue-cli-plugin-electron-builder` 这两个我都试了，确实基于新版的脚手架会好点
目前我们企业项目就是 两个项目 一个  `client` 一个 `front` ，其中还牵扯到 `c#` ，由于刚探索 electron ，它们3者之间的通信有点迷 ，一起加油，

**Comment by mengdebiao** [comment]
@yayxs 我司也是类似你们一样的架构，c#单独封装编译成一个 dll 文件，然后 Electron 直接调用 dll 即可
